# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MyProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MyProto.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rMyProto.proto\"\x82\x01\n\x0bSomeMessage\x12\x0f\n\x07\x62oolean\x18\x01 \x01(\x08\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12#\n\x06object\x18\x03 \x01(\x0b\x32\x13.SomeMessage.Object\x12\x0e\n\x06string\x18\x04 \x01(\t\x1a\x1e\n\x06Object\x12\t\n\x01\x61\x18\x01 \x01(\t\x12\t\n\x01\x63\x18\x02 \x01(\tb\x06proto3'
)




_SOMEMESSAGE_OBJECT = _descriptor.Descriptor(
  name='Object',
  full_name='SomeMessage.Object',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='SomeMessage.Object.a', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='c', full_name='SomeMessage.Object.c', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=148,
)

_SOMEMESSAGE = _descriptor.Descriptor(
  name='SomeMessage',
  full_name='SomeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='boolean', full_name='SomeMessage.boolean', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='SomeMessage.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='object', full_name='SomeMessage.object', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='string', full_name='SomeMessage.string', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SOMEMESSAGE_OBJECT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=148,
)

_SOMEMESSAGE_OBJECT.containing_type = _SOMEMESSAGE
_SOMEMESSAGE.fields_by_name['object'].message_type = _SOMEMESSAGE_OBJECT
DESCRIPTOR.message_types_by_name['SomeMessage'] = _SOMEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SomeMessage = _reflection.GeneratedProtocolMessageType('SomeMessage', (_message.Message,), {

  'Object' : _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
    'DESCRIPTOR' : _SOMEMESSAGE_OBJECT,
    '__module__' : 'MyProto_pb2'
    # @@protoc_insertion_point(class_scope:SomeMessage.Object)
    })
  ,
  'DESCRIPTOR' : _SOMEMESSAGE,
  '__module__' : 'MyProto_pb2'
  # @@protoc_insertion_point(class_scope:SomeMessage)
  })
_sym_db.RegisterMessage(SomeMessage)
_sym_db.RegisterMessage(SomeMessage.Object)


# @@protoc_insertion_point(module_scope)
