# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MyProto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rMyProto.proto\"\x82\x01\n\x0bSomeMessage\x12\x0f\n\x07\x62oolean\x18\x01 \x01(\x08\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12#\n\x06object\x18\x03 \x01(\x0b\x32\x13.SomeMessage.Object\x12\x0e\n\x06string\x18\x04 \x01(\t\x1a\x1e\n\x06Object\x12\t\n\x01\x61\x18\x01 \x01(\t\x12\t\n\x01\x63\x18\x02 \x01(\tb\x06proto3')



_SOMEMESSAGE = DESCRIPTOR.message_types_by_name['SomeMessage']
_SOMEMESSAGE_OBJECT = _SOMEMESSAGE.nested_types_by_name['Object']
SomeMessage = _reflection.GeneratedProtocolMessageType('SomeMessage', (_message.Message,), {

  'Object' : _reflection.GeneratedProtocolMessageType('Object', (_message.Message,), {
    'DESCRIPTOR' : _SOMEMESSAGE_OBJECT,
    '__module__' : 'MyProto_pb2'
    # @@protoc_insertion_point(class_scope:SomeMessage.Object)
    })
  ,
  'DESCRIPTOR' : _SOMEMESSAGE,
  '__module__' : 'MyProto_pb2'
  # @@protoc_insertion_point(class_scope:SomeMessage)
  })
_sym_db.RegisterMessage(SomeMessage)
_sym_db.RegisterMessage(SomeMessage.Object)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOMEMESSAGE._serialized_start=18
  _SOMEMESSAGE._serialized_end=148
  _SOMEMESSAGE_OBJECT._serialized_start=118
  _SOMEMESSAGE_OBJECT._serialized_end=148
# @@protoc_insertion_point(module_scope)
